### ISSUE TITLE
Show all terms when list is not too large

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#249] opened 2015-01-22 17:34 UTC
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 25, 2010 23:15:37_

[from discussion with Julie Bosh on 4/15/10]

This is about automatically showing all the terms in the left- or
right-hand side of the mapping editor when the list is not too large. In
other words, without having to explicitly do the search with empty search
field.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=249_

**Comment by carueda** [comment] 2015-11-29 01:38
Closing as won't fix because:

- primarily, the function to get the whole list is there by just clicking search with empty field
- internally, just to determine how big the list is going to be could be time consuming and thus the extra delay just to display the initial mapping widget might seem unexpected by the user
- the overall search functionality is very general, for example allowing to select multiple vocularies to search from; anticipating what the user wants to use for the search doesn't seem well justified
- also, I think it is much less confusing to make the search action explict to the user

**Comment by graybeal** [comment] 2015-12-15 06:47
For me, the expected behavior of the mapping editor is to show actionable content right away, not force the user to identify what the user has to do before anything useful shows up. 

More specifically to your points:
- it is not intuitive to have to click search with empty field, IMHO, and it is considered best UI practice to present available resources when they are known
- if you are concerned about time-to-display, the correct (IMHO again) UI behavior is to initially search for and present just enough terms to fill the initial display; then more terms can be found and loaded while the user is viewing the screen. Look at how most modern UIs (like LinkedIn Connections screen) present a screenful of images -- they don't try to present all 5000 possible connections, or count how many there are, they just scroll to the next set when you're ready.
- the user always wants to start with something, so that he/she can look at and react to something. A blank window is the least meaningful content possible. If the user has only selected one vocabulary (likely 95% of the time), then it's obvious what should be shown. If the user has selected multiple vocabularies, it seems likely they should all be shown; but since only the first twenty terms are visible at first, that may be moot. (See first bullet.)
- The search action is meaningful when there is no meaningful default display. Most of the time, if not all of the time, there is an extremely meaningful default. 

I'm going to reopen this, I think it deserves further consideration.

**Comment by carueda** [comment] 2016-09-04 23:09
Fixed in v3.

(Just clicking the button to select a particular ontology brings all its terms into the corresp selection section.)

**Closed by carueda** 2016-09-04 23:09 UTC
Labels: Addressed_in_ORR3, enhancement, imported, Priority-Medium, vine, wontfix, xdomes
