### ISSUE TITLE
more graceful handling of browser navigation including history

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#321] opened 2015-01-22 17:50 UTC
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2014 22:43:08_

What capability do you want added or improved? Add/modify history handling for the following:

  \#so/*            search ontologies according to given string
  \#st/*            search terms according to given string
  \#bu/*            registered by given username
  \#ba/*            registered by given authority Where do you want this capability to be accessible? ORR What sort of input/command mechanism do you want? Standard navigation via the browser including history handling.
For example: http://mmisw.org/orr/#st/colorimeter should dispatch the "search terms" feature with the search string "colorimeter". What version of the product are you using? ORR Portal 2.0.52 (201406171840)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=321_

**Comment by mmisw** [comment] 2015-01-22 17:50
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2014 23:02:00_

Done.   ORR Portal 2.1.0 (201406180055)

**Status:** Fixed

**Comment by carueda** [comment] 2015-02-18 02:37
We have a regression here, so re-opening.

**Comment by carueda** [comment] 2015-02-18 02:59
Fixed in ORR Portal 2.3.1

Regression was that upon fresh load of the webapp with any of the history tokens operating on the list of ontologies, the intended dispatch was not occurring. Fix was to trigger the history change after loading such list of ontologies.

(there might be some flickering between the loading of the ontology list and the application of the operation)

**Closed by carueda** 2015-02-18 02:59 UTC
Labels: 1 star, enhancement, imported, mmiorr, Priority-High, Usability
