### ISSUE TITLE
namespace declarations for rdf documents

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#151] opened 2015-01-22 17:07 UTC
_From [smrTucson@gmail.com](https://code.google.com/u/smrTucson@gmail.com/) on June 17, 2009 08:29:35_

What capability do you want added or improved? 
Namespace prefixes in RDF documents for vocabularies should have xmlns
URI's to provide some indication of where they came from. 

Where do you want this capability to be accessible? 
When I access a vocabulary in rdf format through the vocabulary browser. 

What sort of input/command mechanism do you want? 

What is the desired output (content, format, location)? 

rdf:RDF base="" xmlns:omvmmi="" ... 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=151_

**Comment by mmisw** [comment] 2015-01-22 17:07
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2009 15:20:46_

Thanks for entering this enhancement request.
Would it be possible to provide more details? Perhaps commenting on the way is
currently done in voc2rdf (I guess you are referring to the voc2rdf conversion
service). Also, perhaps if you can describe a simple but complete example, that would
be very useful information toward implementing this feature.   Thanks again.  --carlos

**Comment by mmisw** [comment] 2015-01-22 17:07
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on July 13, 2009 10:39:32_

How are you checking the RDF contents? I just realized that some browsers (eg.
firefox, the one I usually use) omit the namespace declarations when displaying the
RDF tree. I always select "Show source" to check the contents. Please let us know any
new comments you have for this issue in order to proceed.

**Comment by mmisw** [comment] 2015-01-22 17:07
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 03, 2009 10:30:48_

**Status:** NeedMoreInfo  
  **Labels:** -Priority-Medium Priority-Low

**Comment by carueda** [comment] 2015-11-30 20:59
Closing as "cannot reproduce".  We never got further details as requested long ago.

**Closed by carueda** 2015-11-30 20:59 UTC
Labels: 1 star, CannotReproduce, enhancement, imported, Priority-Low, xdomes
