### ISSUE TITLE
mmitest authority not always reflected in browse listing

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#200] opened 2015-01-22 17:20 UTC
_From [cmt1...@gmail.com](https://code.google.com/u/111118716825497141417/) on October 22, 2009 10:22:46_

What steps will reproduce the problem? 
1. upload new ontology file
2. complete metadata - choose mmitest for authority abbreviation
3. submit, register, and browse back to registered ontology file. 

Sometimes (irregularly) the "mmitest" is not reflected with the red "T" in the browse list.  It seems like the ORR doesn't see it as an mmitest file. 

What is the expected output? 

What do you see instead? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=200_

**Comment by mmisw** [comment] 2015-01-22 17:20
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 22, 2009 15:10:12_

This is definitely a bug if it is happening with fully-hosted ontologies: currently,
an ontology is recognized as "testing" by looking at the authority abbrev component
in the URI. For re-hosted ontologies, such a component is not there.  This simple
check strategy needs to be improved in general so it works in all cases.  Ideally,
the "testing" status should captured in an explicit way (via some metadata property,
for example).

**Labels:** portal

**Comment by carueda** [comment] 2015-11-25 00:07
Cannot reproduce so closing as fixed.

**Closed by carueda** 2015-11-25 00:07 UTC
Labels: 1 star, bug, CannotReproduce, imported, portal, Priority-Medium, xdomes
