### ISSUE TITLE
Add button to Add... dialog box in VINE

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#313] opened 2015-01-22 17:49 UTC
_From [grayb...@marinemetadata.org](https://code.google.com/u/100453653739559568016/) on April 01, 2013 06:09:09_

What steps will reproduce the problem? 
1. In VINE, one clicks the Add... button to add a new vocabulary for mapping. 
2. Select a vocabulary or enter it in the URL window.
3. Click the Close button. 

What is the expected output/behavior? 
The selected or added vocabulary is processed and added to the list. 

What do you see instead? 
The window just closes.  

Suggest there be two button, one that says "OK" or "Process" or "Choose" (that's the right one) and another one that says "Cancel" (since I can't see any way to process a new vocabulary without closing the window, Cancel is appropriate when nothing will be processed). 

What version of the product are you using? (You can see the version in the lower left corner of the ORR page.)
ORR Portal 2.0.42.beta (201302221022) 

If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.). 

If possible and relevant, please provide a screen shot showing the problem. Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=313_

**Comment by mmisw** [comment] 2015-01-22 17:49
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 08, 2013 18:52:10_

Agree, the interface is confusing!  Thanks for the suggestion.

**Status:** Accepted  
  **Owner:** caru...@gmail.com

**Comment by carueda** [comment] 2015-11-20 00:20
Close this one without changes in the code because:
- unfortunately, no screenshots were provided to help reproduce the issue
- cannot reproduce according to what I can understand from the description.
- The Add behavior has been pretty acceptable IMO.
Probably the Vine interface was improved after this entry(?)

Re-open with more details if this is still an issue.

**Closed by carueda** 2015-11-20 00:20 UTC
Labels: bug, Component-UI, imported, Priority-Medium, Usability, vine, xdomes
