### ISSUE TITLE
Upload date and Version data don't agree

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#60] opened 2015-01-22 16:39 UTC
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 15, 2008 21:16:07_

What steps will reproduce the problem? 
1. Edit metadata for an ontology after 4 PM Pacific time.
2. Look at Version and Upload Time in Browse page. 
3. 

What is the expected output? 
Dates in those two fields should agree. 

What do you see instead? 
Upload time appears to be in local time -- it is a day before the Version. (Look at CF for example.) 

Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=60_

**Comment by mmisw** [comment] 2015-01-22 16:39
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 19, 2008 10:06:43_

**Labels:** aquaportal org.mmisw.ontmd

**Comment by mmisw** [comment] 2015-01-22 16:39
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 29, 2008 16:59:50_

**Labels:** -org.mmisw.ontmd ontmd

**Comment by mmisw** [comment] 2015-01-22 16:39
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:04:18_

**Owner:** grayb...@marinemetadata.org

**Comment by carueda** [comment] 2015-11-23 05:32
John, I just marked this NeedMoreInfo in case you can reproduce.

**Comment by graybeal** [comment] 2015-11-29 23:35
Upload time isn't shown in the browse page any more, so can't reproduce it in the usual way. 

Given time we could look at the upload time in the database (or in the code) to see if it is being stored in local time, rather than UT.

**Comment by graybeal** [comment] 2015-12-15 06:51
I'd like this to be investigated by code review or database inspection, as time allows. (Hmm -- seems to me there is a way to look at the DB contents, maybe you can remind me of that offline and I can check this with that.)  Assigning it back to you Carlos.

**Comment by carueda** [comment] 2017-02-17 03:05
Closing as cannot reproduce.  If problem arises in new ORR3, open issue there.

**Closed by carueda** 2017-02-17 03:05 UTC
Labels: aquaportal, bug, CannotReproduce, imported, NeedMoreInfo, ontmd, Priority-Medium, xdomes
